### ISSUE TITLE
`update_{min,max}` fail if `val` is None

### ISSUE THREAD

**Issue by jonashaag** [apache/iceberg-python#337]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

This code covers the case that `self.current_{min,max}` is None but not that `val` is None

https://github.com/apache/iceberg-python/blob/b7cf14e3b195064d8740b8f2ab306d8729e54dc2/pyiceberg/io/pyarrow.py#L1336-L1340

**Comment by Fokko** [comment]
Thanks for raising this @jonashaag. This seems like a serious issue. Do you have a stack trace or some lines to reproduce it? That would be very helpful.

**Comment by jonashaag** [comment]
Reproducer (here with strings)

```py
schema = Schema(NestedField(1, "col1", StringType(), required=False))
tbl = create_table(..., schema)
arrow_schema = schema_to_pyarrow(tbl.schema())
tbl.append(
    pyarrow.Table.from_pylist([{}], schema=arrow_schema)
)
```

**Comment by jonashaag** [comment]
@Fokko @syun64 this didn't actually fix my bug, I can still reproduce

<img width="1029" alt="Screenshot 2024-02-06 at 09 42 12" src="https://github.com/apache/iceberg-python/assets/175722/5a0097e6-3c3c-444e-ae62-5a0f53f535b9">

**Comment by syun64** [comment]
Hey, thank you for flagging this again. I think we must have misunderstood the problem at first:

the issue here is that current_{min, max} is not None and that val is None, possible because the minimum value within the row groups are different. 

`min(date(2024, 2, 4), None`

raises the same exception as above (the order of the comparison objects is reversed for the min operator).

I think the fix is clear here now that we understand the issue… @Fokko do you agree that we need to generate a next RC for this issue?
