### ISSUE TITLE
Distributed writes in the same iceberg transaction

### ISSUE THREAD

**Issue by rahij** [apache/iceberg-python#357]
### Feature Request / Improvement

I am trying to understand how the new arrow write API can work with distributed writes similar to spark. I have a use case where from different machines, I would like to write a separate arrow dataset that all get committed in the same iceberg transaction. I assume this should be theoretically possible as it works with spark, but I was wondering if there are any plans to support this in the arrow write API. Thanks!

**Comment by Fokko** [comment]
Hey @rahij This is something that we're planning on supporting. I know that the folks at Daft are already working on this. Out of curiosity, how much data are we talking about, and what's the partitioning scheme? Since you probably can hold it in memory, a non-distributed write would also be an option?

**Comment by jimmyxie-figma** [comment]
Any update on supporting distributed write, we are also interested in adding iceberg write capability to Ray. 
https://github.com/ray-project/ray/issues/49032
