### ISSUE TITLE
Race condition on `Table.scan` with `limit`

### ISSUE THREAD

**Issue by bigluck** [apache/iceberg-python#542]
### Apache Iceberg version

0.6.0 (latest release)

### Please describe the bug 🐞

I'm facing a race condition when doing `table.scan` on my code. For some strange reason, the code exits before getting the final table.

This is my code:
```python
from pyiceberg.table import StaticTable
from pyiceberg.expressions import AlwaysTrue


table = StaticTable.from_metadata(
    metadata_location='s3a://my_s3_bucket/iceberg/taxi_fhvhv_7eba066f-7498-4a8a-b932-bf2dbcc938fd/meta...',
)
res = table.scan(
    selected_fields=("*",),
    row_filter=AlwaysTrue(),
    limit=10_000,
)

print('A >>', res)

a_res = res.to_arrow()
print('B >>', a_res)
print('C >>', a_res.num_rows)
```

Which returns:
```
root@45daaeef1ce1:/# python test.py
A >> <pyiceberg.table.DataScan object at 0x7fece38ec6d0>
B >> pyarrow.Table
hvfhs_license_num: string
dispatching_base_num: string
originating_base_num: string
request_datetime: timestamp[us, tz=UTC]
on_scene_datetime: timestamp[us, tz=UTC]
pickup_datetime: timestamp[us, tz=UTC]
dropoff_datetime: timestamp[us, tz=UTC]
PULocationID: int64
DOLocationID: int64
trip_miles: double
trip_time: int64
base_passenger_fare: double
tolls: double
bcf: double
sales_tax: double
congestion_surcharge: double
airport_fee: int32
tips: double
driver_pay: double
shared_request_flag: string
shared_match_flag: string
access_a_ride_flag: string
wav_request_flag: string
wav_match_flag: string
----
hvfhs_license_num: []
dispatching_base_num: []
originating_base_num: []
request_datetime: []
on_scene_datetime: []
pickup_datetime: []
dropoff_datetime: []
PULocationID: []
DOLocationID: []
trip_miles: []
...
C >> 0
```

I think the problem happens here: 
https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1021-L1023

The code modifies the `row_counts` array before returning the table, but if multiple tasks are running concurrently, the next task that starts executing the `_task_to_table` function will return `None` due to 

https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L941-L954

I think it happens because the original task with the data is still processing the content of the table here: https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1023

So now, I suppose, what happens is that the task that returned `None` is processed before the real task with the table content, indeed the `completed_futures` list now contains only a task with `None`, witch course the code to return an empty table:

https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1111C1-L1116C18

This is the content of the `completed_futures` & `tables` variables on the `project_table` fn:
```
>>>>> completed_futures SortedKeyList([<Future at 0x7fa7e4b97fd0 state=finished returned NoneType>], key=<function project_table.<locals>.<lambda> at 0x7fa90316c4a0>)
>>>>> tables []
```

And by modifying the loop with:
```python
    # for consistent ordering, we need to maintain future order
    futures_index = {f: i for i, f in enumerate(futures)}
    completed_futures: SortedList[Future[pa.Table]] = SortedList(iterable=[], key=lambda f: futures_index[f])
    for future in concurrent.futures.as_completed(futures):
        completed_futures.add(future)

        # stop early if limit is satisfied
        if limit is not None and sum(row_counts) >= limit:
            print('>>>>> ', limit, sum(row_counts), future.result())
            break
```

I got:
```
>>>>>  10000 10000 None
```

**Comment by kevinjqliu** [comment]
I asked an AI for answers...
#### Prompt
```
theres a bug in @pyarrow.py function `project_table` and `_task_to_table` 

can you find the bug? it has to do with concurrency 
```

#### Answer
The bug in the [project_table](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1044) and [_task_to_table](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L941) functions within [pyiceberg/io/pyarrow.py](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1) related to concurrency likely stems from the handling of futures and the potential for race conditions or incorrect handling of asynchronous execution. Specifically, the issue could be related to how the futures are managed and how results are collected from these futures.

In the `project_table` function, futures are created and submitted to an executor for asynchronous execution of `_task_to_table` tasks. The results of these futures are then collected and processed. However, there are a few areas where concurrency issues could arise:

1. **Early Termination and Future Cancellation**: The code attempts to stop early if a limit on the number of records is satisfied (`if limit is not None and sum(row_counts) >= limit:`). After this check, it cancels any remaining futures that have not yet completed. This approach assumes that the futures are executed and completed in a specific order, which might not always be the case. Futures could complete in any order, and cancelling futures prematurely could lead to incomplete processing or missed data.

    ```python
    if limit is not None:
        _ = [f.cancel() for f in futures if not f.done()]
    ```

2. **Inconsistent Ordering and Result Collection**: The futures are stored in a `SortedList` based on their submission order to ensure consistent ordering. However, the actual execution order of these futures is not guaranteed, and relying on the submission order for processing results could lead to inconsistencies, especially if the task execution times vary significantly.

    ```python
    completed_futures: SortedList[Future[pa.Table]] = SortedList(iterable=[], key=lambda f: futures_index[f])
    ```

3. **Shared State Management (`row_counts`)**: The `row_counts` list is shared among all tasks and is used to determine when the limit is reached. However, this shared state is updated after each future completes, without proper synchronization. This could lead to race conditions where multiple threads attempt to update the `row_counts` list simultaneously, leading to incorrect counts.

    ```python
    row_counts.append(len(arrow_table))
    ```

To address these issues, consider the following:

- **Reevaluate Early Termination Logic**: Ensure that the logic for early termination and future cancellation correctly accounts for the asynchronous nature of task execution. It may be safer to collect and process all results before deciding whether the limit has been reached, rather than cancelling futures prematurely.

- **Synchronization of Shared State**: If shared state (like `row_counts`) must be updated by multiple tasks, ensure proper synchronization to prevent race conditions. This could involve using thread-safe data structures or explicit locking mechanisms.

- **Ordering of Results**: If the order of results is important, consider collecting all future results first and then sorting or processing them based on the desired criteria, rather than relying on the order of future submission.

These suggestions aim to mitigate potential concurrency issues in the `project_table` and `_task_to_table` functions, ensuring correct and consistent processing of tasks in an asynchronous environment.

**Comment by kevinjqliu** [comment]
So to summarize the above. 
There's a bug with `table.scan` related to Futures execution when a `limit` is set. The bug is related to the order of the Futures returned and the shared state `row_counts`.

When the executor is used to run multiple Futures, each Future checks the shared state `row_counts` first before proceeding. 

The bug is when one Future updates the shared state `row_counts` ([L1021](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1021)). Before this specific Future returns and completes ([L1023](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1023)), another Future check the shared state `row_counts` ([L953](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L953)) and returns first ([L954](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L954)).

This leads to the correct `row_counts` but incorrect `completed_futures` since the Future returned is not the only that modified the `row_counts` ([L1112](https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/pyiceberg/io/pyarrow.py#L1112)).

**Comment by kevinjqliu** [comment]
One potential solution is to have `_task_to_table` return the `row_counts` and not modify a shared list. 
The `row_counts` can be aggregated as Futures complete.
